response_director:
  ros__parameters:
    parameter_prefix: step
    arguments: [initial_commmand, step_command, t_step]
    measurement_duration_modifier: "t_step + 3*measurement_duration"
    signal:
      initial_commmand:
        kind: fixed
        value: 0.0
      step_command:
        kind: fixed
        value: 4.5
      t_step:
        kind: fixed
        value: 1.0
