name: CI mirte-thesis-control

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        ros_distro: [jazzy]
    steps:
      - name: Setup ROS (${{ matrix.ros_distro }})
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: |
            wheel_response_controller
            wheel_response_recorder
            thesis_data_processing
          target-ros2-distro: ${{ matrix.ros_distro }}
